# Generated by Django 4.2.3 on 2023-08-04 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='', max_length=13)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
