# Generated by Django 4.2.3 on 2023-08-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
