# Generated by Django 4.2.3 on 2023-08-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
